title: "Andrew James Pegram"
description: "Stories, releases, lyrics, live, video and images."
future: true

collections:
  stories:
    output: true
    permalink: /news/:name/

  releases:
    output: true
    permalink: /releases/:name/

  lyrics:
    output: true
    permalink: /lyrics/:name/

  tour_dates:
    output: true
    permalink: /tour-dates/:name/

  video:
    output: true
    permalink: /video/:name/

defaults:
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"

  - scope:
      path: ""
      type: "releases"
    values:
      layout: "release"

  - scope:
      path: ""
      type: "lyrics"
    values:
      layout: "lyric"

  - scope:
      path: ""
      type: "tour_dates"
    values:
      layout: "tour-date"

  - scope:
      path: ""
      type: "video"
    values:
      layout: "video"
