title: "Andrew James Pegram"
description: "Stories, releases, lyrics, live, video and images."

collections:
  stories:
    output: true
    permalink: /news/:name/

  releases:
    output: true
    permalink: /releases/:name/

  lyrics:
    output: true
    permalink: /lyrics/:name/

defaults:
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"

  - scope:
      path: ""
      type: "releases"
    values:
      layout: "release"

  - scope:
      path: ""
      type: "lyrics"
    values:
      layout: "lyric"
